// Re-export all query functions for convenience
export { getCategories } from "./getCategories"
export { getProducts } from "./getProducts"
export { getProductsByCategory } from "./getProductsByCategory"
export { getProductById } from "./getProductById"
export { getCatalogs } from "./getCatalogs"
export { getCatalogById } from "./getCatalogById"
export { getHeaders } from "./getHeaders"
export { getHeaderById } from "./getHeaderById"
export { getFAQs } from "./getFAQs"